Adapted to DP2, but has lots of failing tests because DP2 does not yet support it: - System.NotSupportedException : Cannot convert to ByRef types - System.ArgumentException : Target does not implement interface - no mixins
git-svn-id: http://svn.castleproject.org:8080/svn/castle/trunk@3055 73e77b4c-caa6-f847-a29a-24ab75ae54b6